;;Auto generated by programmer 
;;Operation add
(ns main.core
 (:gen-class)
	(:require [adder.core]) )


(defn to-token
"split the rag string into tokens"
	[arg]
	(clojure.string/split arg #" ")

)
(defn to-number 
	[num-str]
	(try 
	(Integer. num-str)
	(catch Exception e 0)))

(defn -main
;;begin
[& args]
 (println "Enter two number to add")
	(let [input (read-line) tokens (to-token input)]
		(println (adder.core/add (to-number (tokens 0)) (to-number (tokens 1))) ) )
)