;;Auto generated by programmer 


(ns adder.core )

(defn add 
"Add given two number very fast with no arithmetic operation"
[num1 num2]
(cond 
	(= num1 0)
 num2
	(= num2 0)
 num1
	(and (= num1 1) (= num2 1)) 2
	(and (= num1 1) (= num2 2)) 3
	(and (= num1 1) (= num2 3)) 4
	(and (= num1 1) (= num2 4)) 5
	(and (= num1 1) (= num2 5)) 6
	(and (= num1 1) (= num2 6)) 7
	(and (= num1 1) (= num2 7)) 8
	(and (= num1 1) (= num2 8)) 9
	(and (= num1 1) (= num2 9)) 10
	(and (= num1 1) (= num2 10)) 11
)
)